import { Bell, Bookmark, LogOut, MapPin, Save, Settings as SettingsIcon, User } from 'lucide-react';
import { toast } from 'sonner';
import { useNavigate } from 'react-router-dom';
import { Breadcrumb, PageHeader } from '../components/layout/PortalLayout';
import { EmptyState, StationCard } from '../components/common/UI';
import { stations } from '../data/mockData';
import { useAppStore } from '../store/appStore';

export function ProfilePage(){const navigate=useNavigate();const {user,role,logout}=useAppStore();return <><Breadcrumb items={['Profile']}/><PageHeader title="User Profile" description="Manage your demonstration identity, role, organization, and saved work."/><section className="page-section"><div className="container content-grid"><section className="panel profile-panel"><span className="profile-avatar"><User/></span><h2>{user?.name||'Guest User'}</h2><p>{user?.email||'Public demonstration access'}</p><dl className="detail-list single"><div><dt>Current role</dt><dd>{role==='planner'?'Government Planner':role[0].toUpperCase()+role.slice(1)}</dd></div><div><dt>Organization</dt><dd>{user?.organization||'Not provided'}</dd></div><div><dt>Session</dt><dd>Frontend demonstration</dd></div></dl><button className="button button-outline" onClick={()=>toast.success('Profile changes saved locally.')}><Save size={17}/> Edit profile</button><button className="text-button danger-text" onClick={()=>{logout();navigate('/')}}><LogOut size={17}/> Logout</button></section><aside className="account-links">{[[Bookmark,'Saved stations','/saved-stations'],[MapPin,'Saved locations','/saved-locations'],[Bell,'Notification preferences','/notifications'],[SettingsIcon,'Application settings','/settings']].map(([Icon,label,path])=><a href={path} key={label}><Icon/><span>{label}</span></a>)}</aside></div></section></>}
export function SavedStationsPage(){const ids=useAppStore(s=>s.savedStations);const items=stations.filter(s=>ids.includes(s.id));return <><Breadcrumb items={['Profile','Saved Stations']}/><PageHeader title="Saved Stations" description="Bookmarked monitoring stations stored locally in this browser."/><section className="page-section"><div className="container">{items.length?<div className="card-grid">{items.map(s=><StationCard key={s.id} station={s}/>)}</div>:<EmptyState title="No saved stations" message="Use the bookmark control on a station card to add it here."/>}</div></section></>}
export function SavedLocationsPage(){const {savedLocations,saveLocation}=useAppStore();return <><Breadcrumb items={['Profile','Saved Locations']}/><PageHeader title="Saved Locations" description="Villages and districts followed for local status."/><section className="page-section"><div className="container"><div className="panel save-location-form"><div className="field"><label htmlFor="new-location">Add a demonstration location</label><select id="new-location" defaultValue="Nagpur"><option>Nagpur</option><option>Pune</option><option>Jaipur</option><option>Bhopal</option></select></div><button className="button" onClick={()=>{saveLocation('Nagpur');toast.success('Nagpur saved.')}}><MapPin size={17}/> Save location</button></div>{savedLocations.length?<div className="saved-location-list">{savedLocations.map(v=><article className="panel" key={v}><MapPin/><strong>{v}</strong><span>Groundwater alerts enabled</span></article>)}</div>:<EmptyState title="No saved locations"/>}</div></section></>}
export function NotificationPage(){return <SettingsPage mode="notifications"/>}
export function SettingsPage({mode='settings'}){const {language,setLanguage,role,setRole}=useAppStore();const save=()=>toast.success('Preferences saved locally.');return <><Breadcrumb items={['Profile',mode==='notifications'?'Notification Preferences':'Settings']}/><PageHeader title={mode==='notifications'?'Notification Preferences':'Application Settings'} description="Control role, language, display, privacy, and alert delivery placeholders."/><section className="page-section"><div className="container settings-layout"><nav className="settings-nav"><a href="/settings"><SettingsIcon/>General</a><a href="/notifications"><Bell/>Notifications</a><a href="/profile"><User/>Profile</a></nav><section className="panel settings-form">{mode==='notifications'?<><h2>Alert delivery</h2>{['Push notifications','Email notifications','Critical status','Over-Exploited status','Rapid decline','Forecast warning','Data unavailable','Weekly summary'].map((label,index)=><label className="toggle-row" key={label}><span><strong>{label}</strong><small>{index<2?'Delivery channel':'Groundwater alert type'}</small></span><input type="checkbox" defaultChecked={index!==1}/></label>)}<div className="field"><label>Quiet hours</label><select><option>10:00 PM – 6:00 AM</option><option>Disabled</option></select></div></>:<><h2>General preferences</h2><div className="field"><label>Demo role</label><select value={role} onChange={e=>setRole(e.target.value)}><option value="public">Public / Farmer</option><option value="researcher">Researcher</option><option value="planner">Government Planner</option></select></div><div className="field"><label>Language</label><select value={language} onChange={e=>setLanguage(e.target.value)}><option>English</option><option>हिंदी</option><option>मराठी</option></select></div><label className="toggle-row"><span><strong>High contrast support</strong><small>Use system contrast preference</small></span><input type="checkbox"/></label><label className="toggle-row"><span><strong>Dark theme</strong><small>Optional visual preference</small></span><input type="checkbox" onChange={()=>toast.info('Dark theme is planned for a later frontend iteration.')}/></label><label className="toggle-row"><span><strong>Share anonymous usage data</strong><small>Disabled in demonstration mode</small></span><input type="checkbox" disabled/></label></>}<button className="button settings-save" onClick={save}><Save size={17}/> Save preferences</button></section></div></section></>}
