import { useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { CheckCircle2, Download, Filter, MessageSquare } from 'lucide-react';
import { toast } from 'sonner';
import { Breadcrumb, PageHeader } from '../components/layout/PortalLayout';
import { AlertCard, DemoBadge, EmptyState } from '../components/common/UI';
import { alerts } from '../data/mockData';
import { useAppStore } from '../store/appStore';

export default function AlertsPage(){const [severity,setSeverity]=useState('');const [status,setStatus]=useState('');const {alertStatuses,updateAlertStatus}=useAppStore();const filtered=useMemo(()=>alerts.filter(a=>(!severity||a.severity===severity)&&(!status||(alertStatuses[a.id]||a.status)===status)),[severity,status,alertStatuses]);const acknowledge=(id)=>{updateAlertStatus(id,'Acknowledged');toast.success('Alert marked as acknowledged.');};return <><Breadcrumb items={['Alerts']}/><PageHeader title="Groundwater Alerts" description="Review classification changes, rapid declines, forecast warnings, station outages, and improvements."><DemoBadge/></PageHeader><section className="page-section"><div className="container"><div className="filters alert-filters"><div className="field"><label htmlFor="severity">Severity</label><select id="severity" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severities</option>{['critical','high','medium','low'].map(v=><option key={v}>{v}</option>)}</select></div><div className="field"><label htmlFor="alert-status">Status</label><select id="alert-status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>New</option><option>Acknowledged</option><option>Under Review</option><option>Action Initiated</option><option>Resolved</option><option>Dismissed</option></select></div><button className="button" onClick={()=>toast.success('Alert filters applied.')}><Filter size={16}/> Apply filters</button><button className="button button-outline" onClick={()=>{setSeverity('');setStatus('')}}>Reset</button></div>{filtered.length?<div className="alert-list">{filtered.map(a=><AlertCard key={a.id} alert={{...a,status:alertStatuses[a.id]||a.status}} onStatusChange={acknowledge}/>)}</div>:<EmptyState title="No alerts match these filters"/>}</div></section></>}
export function AlertDetailPage(){const {id}=useParams();const alert=alerts.find(a=>a.id===id)||alerts[0];const {alertStatuses,updateAlertStatus}=useAppStore();const currentStatus=alertStatuses[alert.id]||alert.status;return <><Breadcrumb items={['Alerts',alert.title]}/><PageHeader eyebrow={`${alert.severity} severity`} title={alert.title} description={`${alert.district}, ${alert.state} · ${new Date(alert.createdAt).toLocaleString('en-IN')}`}/><section className="page-section"><div className="container content-grid"><section className="panel"><h2>Alert evidence</h2><dl className="detail-list single"><div><dt>Status</dt><dd>{currentStatus}</dd></div><div><dt>Trigger reason</dt><dd>{alert.description}</dd></div><div><dt>Current value</dt><dd>{alert.currentValue}</dd></div><div><dt>Previous value</dt><dd>{alert.previousValue}</dd></div><div><dt>Forecast impact</dt><dd>Decline may continue over the next four weeks.</dd></div><div><dt>Related station</dt><dd>{alert.stationId}</dd></div></dl><h3>Recommended action</h3><p>{alert.recommendedAction}</p></section><aside className="panel"><h2>Review actions</h2><div className="stacked-actions"><button className="button" onClick={()=>{updateAlertStatus(alert.id,'Acknowledged');toast.success('Alert acknowledged.')}}><CheckCircle2 size={17}/> Acknowledge</button><button className="button button-outline" onClick={()=>{updateAlertStatus(alert.id,'Under Review');toast.success('Alert moved to Under Review.')}}><MessageSquare size={17}/> Mark under review</button><button className="button button-outline" onClick={()=>toast.info('Internal note saved locally for this demo.')}><MessageSquare size={17}/> Add internal note</button><button className="button button-outline" onClick={()=>toast.success('Alert summary prepared.')}><Download size={17}/> Download summary</button></div></aside></div></section></>}
