import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Landmark, LockKeyhole, Sprout, User, FlaskConical } from 'lucide-react';
import { toast } from 'sonner';
import { authService } from '../services/groundwater.service';
import { useAppStore } from '../store/appStore';

const loginSchema=z.object({identifier:z.string().min(3,'Enter a valid email or mobile number.'),password:z.string().min(6,'Password must contain at least 6 characters.'),role:z.enum(['researcher','planner'])});
export function LoginPage(){const navigate=useNavigate();const setUser=useAppStore(s=>s.setUser);const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(loginSchema),defaultValues:{identifier:'researcher@demo.in',password:'demo123',role:'researcher'}});const submit=async values=>{const response=await authService.login(values);localStorage.setItem('jaldrishti-session',response.token);setUser(response.user);toast.success('Signed in to the demonstration workspace.');navigate(response.user.role==='planner'?'/planner':'/researcher')};return <AuthShell title="Sign in to JalDrishti" subtitle="Researcher and government planning workspaces"><form onSubmit={handleSubmit(submit)}><Field label="Email or mobile number" error={errors.identifier?.message}><input aria-invalid={!!errors.identifier} {...register('identifier')}/></Field><Field label="Password" error={errors.password?.message}><input type="password" aria-invalid={!!errors.password} {...register('password')}/></Field><Field label="Workspace"><select {...register('role')}><option value="researcher">Researcher</option><option value="planner">Government Planner</option></select></Field><div className="auth-links"><label><input type="checkbox"/> Remember me</label><Link to="/forgot-password">Forgot password?</Link></div><button className="button auth-submit" disabled={isSubmitting}><LockKeyhole size={17}/>{isSubmitting?'Signing in…':'Sign in'}</button><button type="button" className="button button-outline auth-submit" onClick={()=>navigate('/role-selection')}>Continue as Guest</button><p>New to JalDrishti? <Link to="/register">Create account</Link></p></form></AuthShell>}
export function RegisterPage(){return <AuthShell title="Create a demonstration account" subtitle="Frontend-only registration for researchers and planners"><SimpleForm fields={['Full name','Email','Mobile number','Organization','State','District']} button="Create account" onSubmit={()=>toast.success('Account created in demonstration mode.')} /><p>Already registered? <Link to="/login">Sign in</Link></p></AuthShell>}
export function ForgotPasswordPage(){return <AuthShell title="Reset your password" subtitle="Enter your registered email or mobile number"><SimpleForm fields={['Email or mobile number']} button="Send verification code" onSubmit={()=>toast.success('Demo verification code: 123456')}/><Link to="/login">Return to sign in</Link></AuthShell>}
export function RoleSelectionPage(){const navigate=useNavigate();const setRole=useAppStore(s=>s.setRole);const roles=[['public',Sprout,'Public / Farmer','Simple local status, advisories, and nearby stations.','/public-status'],['researcher',FlaskConical,'Researcher','Technical readings, calculations, forecasts, and exports.','/researcher'],['planner',Landmark,'Government Planner','District priorities, alerts, and reports.','/planner']];return <div className="role-selection"><Link className="auth-brand" to="/">JalDrishti · जलदृष्टि</Link><span className="eyebrow">Demonstration access</span><h1>Choose your experience</h1><p>You can change roles later in settings.</p><div>{roles.map(([role,Icon,title,text,path])=><button key={role} onClick={()=>{setRole(role);navigate(path)}}><span><Icon/></span><div><h2>{title}</h2><p>{text}</p></div><ArrowRight/></button>)}</div></div>}
function AuthShell({title,subtitle,children}){return <main className="auth-page"><section className="auth-side"><Link className="auth-brand" to="/">JalDrishti · जलदृष्टि</Link><div><span className="eyebrow">Groundwater decision support</span><h1>Evidence for better water decisions.</h1><p>Accessible public information, transparent research data, and district planning tools in one interface.</p></div><small>Demonstration frontend · No real account data is collected</small></section><section className="auth-form"><div><User className="auth-icon"/><h1>{title}</h1><p>{subtitle}</p>{children}</div></section></main>}
function Field({label,error,children}){return <div className="field"><label>{label}</label>{children}{error&&<p className="field-error" role="alert">{error}</p>}</div>}
function SimpleForm({fields,button,onSubmit}){const [values,setValues]=useState({});return <form onSubmit={e=>{e.preventDefault();onSubmit(values)}}>{fields.map(label=><div className="field" key={label}><label>{label}</label><input required value={values[label]||''} onChange={e=>setValues({...values,[label]:e.target.value})}/></div>)}<button className="button auth-submit">{button}</button></form>}
