import { useMemo, useState } from 'react';
import { Download, Plus, Printer, X } from 'lucide-react';
import { toast } from 'sonner';
import { Breadcrumb, PageHeader } from '../components/layout/PortalLayout';
import { DataConfidenceBadge, StatusBadge } from '../components/common/UI';
import { ChartFrame, Hydrograph } from '../components/charts/Charts';
import { forecasts, readings, stations } from '../data/mockData';

export default function ComparisonPage(){const [ids,setIds]=useState(stations.slice(0,3).map(s=>s.id));const [normalized,setNormalized]=useState(false);const selected=useMemo(()=>stations.filter(s=>ids.includes(s.id)),[ids]);const add=(id)=>{if(ids.length>=5)return toast.error('You can compare up to five stations.');if(id&&!ids.includes(id))setIds([...ids,id])};return <><Breadcrumb items={['Researcher','Station Comparison']}/><PageHeader title="Station Comparison" description="Compare hydrographs, recharge, forecast, classification, and data quality for two to five stations."/><section className="page-section"><div className="container"><div className="comparison-selector"><div className="selected-chips">{selected.map(s=><span key={s.id}>{s.name}<button aria-label={`Remove ${s.name}`} onClick={()=>setIds(ids.filter(id=>id!==s.id))}><X size={14}/></button></span>)}</div><label className="add-station"><Plus size={17}/><select defaultValue="" onChange={e=>{add(e.target.value);e.target.value=''}}><option value="" disabled>Add station</option>{stations.filter(s=>!ids.includes(s.id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><div className="comparison-toolbar"><label><input type="checkbox" checked={normalized} onChange={e=>setNormalized(e.target.checked)}/> Normalize values for comparison</label><div><button className="button button-small button-outline" onClick={()=>toast.success('Comparison CSV prepared.')}><Download size={15}/> CSV</button><button className="button button-small button-outline" onClick={()=>toast.success('Comparison JSON prepared.')}><Download size={15}/> JSON</button><button className="button button-small" onClick={()=>window.print()}><Printer size={15}/> Print summary</button></div></div><ChartFrame title="Combined hydrograph" description={`${normalized?'Normalized':'Observed'} station values; select individual stations in the legend`}><Hydrograph readings={readings.filter(r=>r.stationId===ids[0])} forecasts={forecasts.filter(f=>f.stationId===ids[0])}/></ChartFrame><div className="comparison-table"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Station</th><th>Classification</th><th>Water level</th><th>Recharge</th><th>8-week forecast</th><th>Data confidence</th></tr></thead><tbody>{selected.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small className="table-subtext">{s.stationCode}</small></td><td><StatusBadge compact status={s.classification}/></td><td>{s.currentWaterLevel} m bgl</td><td>{s.rechargeEstimate} MCM</td><td>{s.trend}</td><td><DataConfidenceBadge level={s.dataConfidence}/></td></tr>)}</tbody></table></div></div></div></section></>}
