import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { AlertTriangle, Database, Droplets, FileText, RadioTower } from 'lucide-react';
import { Breadcrumb, PageHeader } from '../components/layout/PortalLayout';
import { AlertCard, EmptyState, StatusBadge, SummaryCard, Tabs, TrendIndicator } from '../components/common/UI';
import { ChartFrame, TrendChart } from '../components/charts/Charts';
import { alerts, chartSummary, districts, stations } from '../data/mockData';

export function DistrictListPage(){return <><Breadcrumb items={['District Status']}/><PageHeader title="District Groundwater Status" description="Compare classifications, coverage, trends, and alerts across monitored districts."/><section className="page-section"><div className="container district-grid">{districts.map(d=><a className="district-card" href={`/districts/${d.district.toLowerCase()}`} key={d.district}><div><span>{d.state}</span><h2>{d.district}</h2></div><StatusBadge status={d.classification}/><dl><div><dt>Stations</dt><dd>{d.stationCount}</dd></div><div><dt>Coverage</dt><dd>{d.dataCoverage}%</dd></div><div><dt>Active alerts</dt><dd>{d.activeAlerts}</dd></div></dl><TrendIndicator trend={d.trend}/></a>)}</div></section></>}
export default function DistrictPage(){const {slug}=useParams();const district=districts.find(d=>d.district.toLowerCase()===slug)||districts[0];const [active,setActive]=useState('Summary');const localStations=stations.filter(s=>s.district===district.district);const localAlerts=alerts.filter(a=>a.district===district.district);return <><Breadcrumb items={['Districts',district.district]}/><PageHeader eyebrow={district.state} title={`${district.district} District Summary`} description="Current groundwater decision summary with trends, alerts, station coverage, and recommended actions."/><section className="page-section"><div className="container"><div className="district-status-banner"><div><span>Current district classification</span><StatusBadge status={district.classification}/></div><div><span>Previous classification</span><StatusBadge status={district.previousClassification}/></div><div><span>Current trend</span><TrendIndicator trend={district.trend}/></div><p><strong>Recommended action:</strong> Review high-risk blocks, validate declining stations, and prioritize demand management and recharge measures.</p></div><div className="summary-grid district-metrics"><SummaryCard icon={RadioTower} label="Monitored stations" value={district.stationCount} support="Within district"/><SummaryCard icon={Droplets} label="Average water level" value={`${district.averageWaterLevel} m`} support="Below ground level"/><SummaryCard icon={Database} label="Data coverage" value={`${district.dataCoverage}%`} support="Current period"/><SummaryCard icon={AlertTriangle} label="Active alerts" value={district.activeAlerts} support="Requires review"/></div><Tabs tabs={['Summary','Stations','Trends','Alerts','Reports']} active={active} onChange={setActive}/>{active==='Summary'&&<div className="content-grid"><ChartFrame title="District water-level trend"><TrendChart data={chartSummary}/></ChartFrame><section className="panel"><h2>High-risk blocks</h2>{district.highRiskBlocks.map(block=><div className="risk-block" key={block}><AlertTriangle/><span><strong>{block}</strong><small>Declining trend · review recommended</small></span></div>)}</section></div>}{active==='Stations'&&(localStations.length?<div className="card-grid">{localStations.map(s=><article className="panel" key={s.id}><h3>{s.name}</h3><StatusBadge status={s.classification}/><p>{s.currentWaterLevel} m below ground level</p></article>)}</div>:<EmptyState/>)}{active==='Trends'&&<ChartFrame title="Groundwater and recharge trend"><TrendChart data={chartSummary}/></ChartFrame>}{active==='Alerts'&&(localAlerts.length?<div className="card-grid">{localAlerts.map(a=><AlertCard key={a.id} alert={a}/>)}</div>:<EmptyState title="No active district alerts"/>)}{active==='Reports'&&<section className="state-panel"><FileText/><h2>Create a district report</h2><p>Generate a printable summary using the current demonstration data.</p><a className="button" href="/reports">Open report builder</a></section>}</div></section></>}
