import { Activity, AlertTriangle, ArrowRight, BookOpen, CheckCircle2, CloudRain, Database, Droplets, FileBarChart, FlaskConical, Gauge, Landmark, Map, MapPin, RadioTower, Search, ShieldCheck, Sprout, Users, Waves } from 'lucide-react';
import { useNavigate, Link } from 'react-router-dom';
import { useState } from 'react';
import { alerts, LAST_SYNC, stations } from '../data/mockData';
import { AlertCard, classificationMessage, DemoBadge, StatusBadge, SummaryCard } from '../components/common/UI';
import StationMap from '../components/maps/StationMap';

const overview = [
  [RadioTower, 'Monitoring stations', stations.length, 'Across 3 demonstration states', 'default'],
  [Activity, 'Active stations', stations.filter((s) => s.status === 'active').length, 'Reporting within 48 hours', 'default'],
  [CheckCircle2, 'Safe stations', stations.filter((s) => s.classification === 'safe').length, 'Sustainable range', 'safe'],
  [Gauge, 'Semi-Critical', stations.filter((s) => s.classification === 'semi-critical').length, 'Careful use advised', 'semi'],
  [AlertTriangle, 'Critical stations', stations.filter((s) => s.classification === 'critical').length, 'Attention recommended', 'critical'],
  [Waves, 'Over-Exploited', stations.filter((s) => s.classification === 'over-exploited').length, 'Urgent action required', 'over'],
  [Map, 'States covered', 3, 'Maharashtra, Rajasthan, MP', 'default'],
  [Database, 'Last synchronized', '06:00', '14 July 2026 (IST)', 'default'],
];

export default function HomePage() {
  const [search, setSearch] = useState('');
  const navigate = useNavigate();
  const submit = (event) => { event.preventDefault(); navigate(`/stations?q=${encodeURIComponent(search)}`); };
  return <>
    <section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><DemoBadge /><span className="eyebrow">National groundwater information</span><h1>Know the Groundwater Condition in Your Area</h1><p>Access groundwater status, trends, forecasts, recharge estimates, and early warnings using Digital Water Level Recorder data.</p><form className="hero-search" onSubmit={submit}><Search aria-hidden="true" /><label className="sr-only" htmlFor="home-search">Search by village, district, state, PIN code, or station</label><input id="home-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Village, district, state, PIN code, or station"/><button type="submit">Check Groundwater Status</button></form><div className="hero-actions"><Link className="button button-secondary" to="/public-status"><MapPin size={18}/> Check My Area</Link><Link className="button button-outline" to="/map"><Map size={18}/> Explore National Map</Link></div><p className="sync-line"><Database size={15}/> Last data synchronization: {LAST_SYNC}</p></div><div className="hero-data" aria-label="National groundwater briefing"><div className="briefing-head"><span>National briefing</span><strong>14 July 2026</strong></div><div className="water-depth"><Droplets/><div><span>Average monitored depth</span><strong>10.8 <small>m bgl</small></strong><p>0.4 m deeper than last month</p></div></div><div className="briefing-row"><span>Station availability</span><strong>91%</strong></div><div className="briefing-row"><span>Active priority alerts</span><strong>{alerts.filter((a) => ['critical','high'].includes(a.severity)).length}</strong></div><div className="briefing-note"><ShieldCheck size={18}/><span>Decision-support information<br/><small>Not a regulatory declaration</small></span></div></div></div></section>
    <section className="page-section"><div className="container"><div className="section-head"><div><span className="eyebrow">National overview</span><h2>Groundwater monitoring at a glance</h2><p>A current summary of the demonstration monitoring network.</p></div><DemoBadge /></div><div className="summary-grid">{overview.map(([icon,label,value,support,tone]) => <SummaryCard key={label} icon={icon} label={label} value={value} support={support} tone={tone}/>)}</div></div></section>
    <section className="page-section page-section-white"><div className="container"><div className="section-head"><div><span className="eyebrow">Explore geographically</span><h2>Groundwater monitoring map</h2><p>View classification and station status across the demonstration states.</p></div><Link className="button button-outline" to="/map">View full map <ArrowRight size={17}/></Link></div><StationMap compact stations={stations}/></div></section>
    <section className="page-section"><div className="container"><div className="section-head"><div><span className="eyebrow">Understanding status</span><h2>What do the classifications mean?</h2><p>Classification combines recharge and groundwater extraction indicators.</p></div></div><div className="condition-grid">{['safe','semi-critical','critical','over-exploited'].map((status) => <article className={`condition-card condition-${status}`} key={status}><StatusBadge status={status}/><p>{classificationMessage[status]}</p><strong>{status === 'safe' ? 'Continue efficient water use.' : status === 'semi-critical' ? 'Avoid additional extraction.' : status === 'critical' ? 'Prioritize conservation measures.' : 'Implement urgent recharge and demand controls.'}</strong></article>)}</div></div></section>
    <section className="page-section page-section-white"><div className="container"><div className="section-head"><div><span className="eyebrow">Services by user</span><h2>Information designed for every role</h2></div></div><div className="role-grid"><article><span><Sprout/></span><h3>Public and Farmers</h3><p>Check local groundwater status, trends, advisories, and nearby monitoring stations.</p><Link className="text-link" to="/public-status">Check My Area <ArrowRight size={16}/></Link></article><article><span><FlaskConical/></span><h3>Researchers</h3><p>Explore processed station data, hydrographs, recharge calculations, forecasts, and exports.</p><Link className="text-link" to="/researcher">Open Data Explorer <ArrowRight size={16}/></Link></article><article><span><Landmark/></span><h3>Government Planners</h3><p>Monitor district status, review alerts, compare regions, and generate reports.</p><Link className="text-link" to="/planner">Open Planning Dashboard <ArrowRight size={16}/></Link></article></div></div></section>
    <section className="page-section"><div className="container"><div className="section-head"><div><span className="eyebrow">Early warning</span><h2>Recent groundwater alerts</h2></div><Link className="text-link" to="/alerts">View all alerts <ArrowRight size={16}/></Link></div><div className="card-grid">{alerts.slice(0,3).map((alert) => <AlertCard key={alert.id} alert={alert}/>)}</div></div></section>
    <section className="page-section page-section-white"><div className="container info-split"><div><span className="eyebrow">Data transparency</span><h2>Data sources and processing</h2><p>JalDrishti distinguishes observed, cleaned, reconstructed, calculated, forecast, and cached values. Recharge estimates retain auditable inputs.</p><div className="method-list"><span><Database/> National Water Data Portal</span><span><RadioTower/> DWLR station observations</span><span><CloudRain/> Water Table Fluctuation calculation</span><span><FileBarChart/> Forecast and quality processing</span></div><Link className="button button-outline" to="/data-sources">View Data Sources</Link></div><div className="public-info"><h2>Practical information</h2>{[[BookOpen,'Understanding groundwater'],[Droplets,'Water-saving practices'],[CloudRain,'Rainwater harvesting'],[Sprout,'Efficient irrigation'],[Users,'Frequently asked questions']].map(([Icon,label]) => <Link to="/learn" key={label}><Icon/><span>{label}</span><ArrowRight/></Link>)}</div></div></section>
    <section className="important-links"><div className="container"><h2>Important links</h2><p>Reference organizations (links intentionally omitted in demonstration mode).</p><div>{['Central Ground Water Board','National Water Data Portal','Ministry of Jal Shakti','India Water Resources Information System','State groundwater departments'].map((label) => <button key={label} onClick={() => window.alert(`${label}: verified external URL will be configured during deployment.`)}>{label}<ArrowRight size={16}/></button>)}</div></div></section>
  </>;
}
