import { useMemo, useState } from 'react';
import { List, Map as MapIcon, RotateCcw, Search } from 'lucide-react';
import { Breadcrumb, PageHeader } from '../components/layout/PortalLayout';
import { DemoBadge, EmptyState, StationCard } from '../components/common/UI';
import StationMap from '../components/maps/StationMap';
import { stations } from '../data/mockData';

export default function MapPage() {
  const [filters, setFilters] = useState({ search:'', state:'', district:'', classification:'', trend:'', status:'' });
  const [view, setView] = useState('map');
  const [selected, setSelected] = useState(null);
  const set = (key, value) => setFilters((current) => ({ ...current, [key]: value, ...(key === 'state' ? { district: '' } : {}) }));
  const filtered = useMemo(() => stations.filter((station) => (!filters.search || `${station.name} ${station.stationCode} ${station.village}`.toLowerCase().includes(filters.search.toLowerCase())) && (!filters.state || station.state === filters.state) && (!filters.district || station.district === filters.district) && (!filters.classification || station.classification === filters.classification) && (!filters.trend || station.trend === filters.trend) && (!filters.status || station.status === filters.status)), [filters]);
  const options = (key) => [...new Set(stations.filter((s) => key !== 'district' || !filters.state || s.state === filters.state).map((s) => s[key]))];
  return <><Breadcrumb items={['Groundwater Map']}/><PageHeader title="Groundwater Map" description="Explore station classifications, trends, and data availability across the demonstration monitoring network."><DemoBadge/></PageHeader><section className="page-section map-page"><div className="container"><div className="filters map-filters"><div className="field"><label htmlFor="map-search">Search station or place</label><input id="map-search" value={filters.search} onChange={(e) => set('search',e.target.value)} placeholder="Station, village, or code"/></div>{[['state','State'],['district','District'],['classification','Classification'],['trend','Trend'],['status','Sensor status']].map(([key,label]) => <div className="field" key={key}><label htmlFor={`map-${key}`}>{label}</label><select id={`map-${key}`} value={filters[key]} onChange={(e) => set(key,e.target.value)}><option value="">All</option>{options(key).map((option) => <option key={option} value={option}>{option}</option>)}</select></div>)}<button className="button button-outline" onClick={() => setFilters({search:'',state:'',district:'',classification:'',trend:'',status:''})}><RotateCcw size={16}/> Reset</button></div><div className="map-toolbar"><span><strong>{filtered.length}</strong> stations shown · Last updated 14 July 2026, 6:00 AM</span><div className="segmented"><button className={view==='map'?'active':''} onClick={() => setView('map')}><MapIcon size={16}/> Map</button><button className={view==='list'?'active':''} onClick={() => setView('list')}><List size={16}/> List</button></div></div>{filtered.length === 0 ? <EmptyState/> : view === 'map' ? <div className="map-with-panel"><StationMap stations={filtered} onSelect={setSelected}/>{selected && <aside className="selected-station"><button className="panel-close" onClick={() => setSelected(null)} aria-label="Close station preview">×</button><StationCard station={selected}/></aside>}<button className="search-area button button-small"><Search size={15}/> Search this area</button></div> : <div className="card-grid">{filtered.map((station) => <StationCard key={station.id} station={station}/>)}</div>}<p className="map-source">Map © OpenStreetMap contributors · Station locations and values are demonstration data.</p></div></section></>;
}
