import { lazy, Suspense } from 'react';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import PortalLayout from './components/layout/PortalLayout';
import { LoadingSkeleton } from './components/common/UI';

const Home=lazy(()=>import('./pages/HomePage')); const PublicStatus=lazy(()=>import('./pages/PublicStatusPage')); const MapPage=lazy(()=>import('./pages/MapPage')); const Stations=lazy(()=>import('./pages/StationsPage')); const StationDetail=lazy(()=>import('./pages/StationDetailPage')); const Researcher=lazy(()=>import('./pages/ResearcherPage')); const Compare=lazy(()=>import('./pages/ComparisonPage')); const Planner=lazy(()=>import('./pages/PlannerPage')); const District=lazy(()=>import('./pages/DistrictPage')); const DistrictList=lazy(()=>import('./pages/DistrictPage').then(m=>({default:m.DistrictListPage}))); const Alerts=lazy(()=>import('./pages/AlertsPage')); const AlertDetail=lazy(()=>import('./pages/AlertsPage').then(m=>({default:m.AlertDetailPage}))); const Reports=lazy(()=>import('./pages/ReportsPage')); const Export=lazy(()=>import('./pages/ExportPage')); const About=lazy(()=>import('./pages/InformationPages').then(m=>({default:m.AboutPage}))); const DataSources=lazy(()=>import('./pages/InformationPages').then(m=>({default:m.DataSourcesPage}))); const Learn=lazy(()=>import('./pages/InformationPages').then(m=>({default:m.LearnPage}))); const Help=lazy(()=>import('./pages/InformationPages').then(m=>({default:m.HelpPage}))); const Login=lazy(()=>import('./pages/AuthPages').then(m=>({default:m.LoginPage}))); const Register=lazy(()=>import('./pages/AuthPages').then(m=>({default:m.RegisterPage}))); const Forgot=lazy(()=>import('./pages/AuthPages').then(m=>({default:m.ForgotPasswordPage}))); const Role=lazy(()=>import('./pages/AuthPages').then(m=>({default:m.RoleSelectionPage}))); const Profile=lazy(()=>import('./pages/AccountPages').then(m=>({default:m.ProfilePage}))); const SavedStations=lazy(()=>import('./pages/AccountPages').then(m=>({default:m.SavedStationsPage}))); const SavedLocations=lazy(()=>import('./pages/AccountPages').then(m=>({default:m.SavedLocationsPage}))); const Notifications=lazy(()=>import('./pages/AccountPages').then(m=>({default:m.NotificationPage}))); const Settings=lazy(()=>import('./pages/AccountPages').then(m=>({default:m.SettingsPage}))); const NotFound=lazy(()=>import('./pages/NotFoundPage'));

const routes=[{element:<PortalLayout/>,children:[{path:'/',element:<Home/>},{path:'/public-status',element:<PublicStatus/>},{path:'/map',element:<MapPage/>},{path:'/stations',element:<Stations/>},{path:'/stations/:id',element:<StationDetail/>},{path:'/researcher',element:<Researcher/>},{path:'/compare',element:<Compare/>},{path:'/exports',element:<Export/>},{path:'/planner',element:<Planner/>},{path:'/districts',element:<DistrictList/>},{path:'/districts/:slug',element:<District/>},{path:'/alerts',element:<Alerts/>},{path:'/alerts/:id',element:<AlertDetail/>},{path:'/reports',element:<Reports/>},{path:'/data-sources',element:<DataSources/>},{path:'/learn',element:<Learn/>},{path:'/about',element:<About/>},{path:'/help',element:<Help/>},{path:'/profile',element:<Profile/>},{path:'/saved-stations',element:<SavedStations/>},{path:'/saved-locations',element:<SavedLocations/>},{path:'/notifications',element:<Notifications/>},{path:'/settings',element:<Settings/>}]},{path:'/login',element:<Login/>},{path:'/register',element:<Register/>},{path:'/forgot-password',element:<Forgot/>},{path:'/role-selection',element:<Role/>},{path:'*',element:<NotFound/>}];
const router=createBrowserRouter(routes);
export default function App(){return <Suspense fallback={<div className="container route-loading"><LoadingSkeleton rows={4}/></div>}><RouterProvider router={router}/></Suspense>}
